[project]
name = "fwParser"
description = "A simple parser for fixed width files!"
keywords = ["text", "fixed width"]
readme = "README.md"
license = "MIT"
version = "0.2.0"
requires-python = ">=3.10"
authors = [
	{name = "Antony G."}
]
maintainers = [
	{name = "Antony G."}
]
dependencies = [
    "faker>=37.5.3",
    "pandas>=2.3.0",
    "polars>=1.31.0",
    "pytest>=8.4.1",
    "tomli>=2.2.1",
]

[dependency-groups]
dev = [
    "faker>=37.5.3",
    "pandas>=2.3.0",
    "polars>=1.31.0",
    "pytest>=8.4.1",
    "tomli>=2.2.1",
]

[project.optional-dependencies]
toml = ["tomli"]
pandas = ["pandas", "tomli"]
polars = ["polars", "tomli"]
all = ["polars", "pandas", "tomli"]
test = ["pandas", "polars", "tomli", "pytest", "Faker"]


[pyproject.urls]
Homepage = "https://github.com/avgra3/fwparser"
Documentation = "https://github.com/avgra3/fwparser/blob/main/README.md"
Repository = "https://github.com/avgra3/fwparser"
"Bug Tracker" = "https://github.com/avgra3/fwparser/issues"

[tools.pytest.ini_options]
pythonpath = "src"


[tool.ruff]
line-length = 88
indent-width = 4
# Set to the minimum supported Python version
target-version = "py310"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"
